import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisScroll from '../components/LenisScroll';
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Ashok Fitness | Online Personal Training & Body Transformation Coach",
//   description: "Generated by create next app",
// };

// import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Train With Ashok | Personal Trainer & Body Transformation Coach",
    template: "%s | Train With Ashok",
  },
  description:
    "Achieve your best body with Train With Ashok — personalized online coaching and in-gym training programs designed to help you lose fat, build muscle, and gain confidence. Train with expert guidance wherever you are.",
  keywords: [
    "Train With Ashok",
    "personal trainer",
    "online personal training",
    "in-gym training",
    "body transformation coach",
    "fitness coach Nepal",
    "fat loss program",
    "muscle building plan",
    "nutrition coaching",
    "custom workout plan",
    "abs training program",
    "fitness coaching",
  ],
  metadataBase: new URL("https://www.trainwithashok.com"), // update when deployed
  alternates: {
    canonical: "https://www.trainwithashok.com",
  },
  openGraph: {
    title: "Train With Ashok | Personal Trainer & Body Transformation Coach",
    description:
      "Train smarter, eat better, and achieve visible results with Train With Ashok. Personalized online coaching and in-gym training to help you reach your fitness goals with expert guidance.",
    url: "https://www.trainwithashok.com",
    siteName: "Train With Ashok",
    images: [
      {
        url: "/og-image.jpg", // recommended 1200x630
        width: 1200,
        height: 630,
        alt: "Train With Ashok | Online & In-Gym Training",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Train With Ashok | Personal Trainer & Body Transformation Coach",
    description:
      "Personalized online coaching and in-gym training programs to help you build strength, lose fat, and transform your body.",
    images: ["/og-image.jpg"],
    creator: "@trainwithashok", // optional: replace with your Twitter handle
  },
  authors: [{ name: "Ashok Trainer", url: "https://www.trainwithashok.com" }],
  creator: "Ashok Trainer",
  publisher: "Train With Ashok",
  category: "Fitness & Personal Coaching",
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <LenisScroll>
          {children}
          
        </LenisScroll>
        
        <Footer />
      </body>
    </html>
  );
}
